### ISSUE TITLE
Collapse in run() method and invoke from __main__

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/mvr-automation#8]
Modify all unindented code into method run() and invoke run() from main():

https://github.com/S3Infosoft/mvr-automation/blob/e989b12ea462d392f467ff2cebda16ffab54d007/src/Common.py#L19

**Comment by sidhshar** [comment]
Also here:

https://github.com/S3Infosoft/mvr-automation/blob/e989b12ea462d392f467ff2cebda16ffab54d007/src/Booking%2BMVR.py#L13

**Comment by gp499** [comment]
Invoked from run() method from main()
