### ISSUE TITLE
Remove hardcoded reference

### ISSUE THREAD

**Issue by sidhshar** [S3Infosoft/mvr-automation#9]
Remove all hard coded paths.

https://github.com/S3Infosoft/mvr-automation/blob/30321a27dec2b9921a4daabb50e11fcc6f868a0e/src/Common.py#L36

Make use of docker based driver such as https://github.com/joyzoursky/docker-python-chromedriver

**Comment by gp499** [comment]
I put the chromedriver.exe in the same directory and referenced it there. Will that do?

**Comment by sidhshar** [comment]
Changed to selenium hub and removed reference.
